import React, { useState } from "react";

import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
	const router = useRouter();
	const [pokemon, setPokemon] = useState("");
	return (
		<div className={styles.container}>
			<Head>
				<title>PokeSearch</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Image
					src='/assets/images/Pokeball.png'
					alt='Pokeball Logo'
					width={144}
					height={144}
				/>
				<h1 className={styles.title}>PokéSearch</h1>
				<div className={styles.pokemonContainer}>
					<input
						type='text'
						id='pokemon'
						name='pokemon'
						placeholder="Enter Pokémon's Name or Id"
						value={pokemon}
						className={styles.pokemonInput}
						onChange={(e) => {
							setPokemon(e.target.value);
						}}
					/>
					<button
						className={styles.pokemonButton}
						onClick={() => router.push(`/pokemon/${pokemon}`)}>
						PokéSearch
					</button>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'></a>
			</footer>
		</div>
	);
};

export default Home;
