import React, { ReactNode, useState } from "react";
import Head from "next/head";
import styles from "./PokesearchTemplate.module.scss";
import Image from "next/image";

import githubIcon from "../../assets/icons/github-icon-50.png";
interface PokesearchTemplate {
	children: ReactNode;
}

const PokesearchTemplate = ({ children }: PokesearchTemplate) => {
	return (
		<div className='PokesearchTemplate'>
			<Head>
				<title>PokeSearch</title>
				<meta property='og:title' content='PokeSearch' key='title' />
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header className={styles["PokesearchTemplate__header"]}>
				<a
					href='https://github.com/realim1/PokeSearch'
					target='_blank'
					rel='noreferrer'>
					<Image src={githubIcon} width={25} height={25} alt='Github Logo' />
				</a>
			</header>
			{children}
			<footer className={styles["PokesearchTemplate__footer"]}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Footer
				</a>
			</footer>
		</div>
	);
};

export default PokesearchTemplate;
